site_name: '@luis__ciber'
site_description: Hi! ğŸ‘‹ I'm Luis Antonio Correa Leyva. Computer Scientist. Software Developer. Developing applications with Flutter and looking for Data Science projects.
site_url: https://luis-ciber.is-a.dev
repo_url: https://github.com/correaleyval
edit_uri: ""

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/avatar.jpg
  favicon: assets/images/avatar.jpg

  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta
  - attr_list
  - toc:
      permalink: ğŸ”—

copyright: Copyright &copy; Luis Correa Leyva

extra:
  disqus: "correaleyval"
  manifest: manifest.json
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/luis-antonio-correa-leyva-605a251a4/
      name: LinkedIn
    
    - icon: fontawesome/brands/github
      link: https://github.com/correaleyval
      name: GitHub
    
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/correaleyval
      name: GitLab
    
    - icon: fontawesome/solid/code
      link: https://profile.codersrank.io/user/correaleyval
      name: Codersrank

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/luis__ciber
      name: Twitter

    - icon: fontawesome/brands/telegram
      link: https://t.me/luis_ciber
      name: Telegram

    - icon: fontawesome/solid/paper-plane
      link: mailto:correaleyval@gmail.com
      name: Gmail

nav:
  - â­Start:
      - ğŸ‘‹ Hello World!: index.md
      - ğŸ“„ Latests posts: blog/index.md
      - ğŸ’» Applications and projects: apps/index.md
      - ğŸ—’ Notebooks: notebooks/index.md
      - â„¹ï¸ Contact: contact/index.md
  - Blog: blog/index.md
  - All posts: 
    - Desarrollo rÃ¡pido en Flutter con GetX: blog/2020/03/07/desarrollo-rÃ¡pido-en-flutter-con-getx/index.md
  - Notebooks: notebooks/index.md
  - Applications and projects: apps/index.md
  - Contact: contact/index.md

plugins:
  - mkdocs-jupyter:
      execute: False
      include_source: True
