site_name: '@luis_ciber'
site_description: Hola! ğŸ‘‹ Soy Luis Correa @luis_ciber ğŸ§‘â€ğŸ’». Computer Scientist. ğŸ’» Desarrollador de software. ğŸš€ "Ciber Emprendedor".
site_url: https://luis-ciber.is-a.dev
repo_url: https://github.com/correaleyval
edit_uri: ""

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/face.png
  favicon: assets/images/face.png

  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta
  - attr_list
  - toc:
      permalink: ğŸ”—

copyright: Copyright &copy; Luis Correa Leyva

extra:
  disqus: "correaleyval"
  manifest: manifest.json
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/luisciber
      name: LinkedIn
    
    - icon: fontawesome/brands/github
      link: https://github.com/correaleyval
      name: GitHub
    
    # - icon: fontawesome/brands/gitlab
    #   link: https://gitlab.com/correaleyval
    #   name: GitLab
    
    - icon: fontawesome/solid/code
      link: https://profile.codersrank.io/user/correaleyval
      name: Codersrank

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/luis__ciber
      name: Twitter

    - icon: fontawesome/brands/telegram
      link: https://t.me/luis_ciber
      name: Telegram

    - icon: fontawesome/solid/paper-plane
      link: mailto:correaleyval@gmail.com
      name: Gmail

nav:
  - â­ Start:
      - ğŸ‘‹ git init: index.md
      - ğŸ“„ Publicaciones recientes: blog/index.md
      - ğŸ’» Aplicaciones y proyectos: apps/index.md
      - ğŸ—’ Notebooks: notebooks/index.md
      - â„¹ï¸ Contacto: contact/index.md
      - ğŸ§‘â€ğŸ’» Coder CV: cv/index.md
  - Blog: blog/index.md
  - Todos los posts: 
    - Desarrollo rÃ¡pido en Flutter con GetX: blog/2020/03/07/desarrollo-rÃ¡pido-en-flutter-con-getx/index.md
  - Notebooks: notebooks/index.md
  - Aplicaciones y proyectos: apps/index.md
  - Contacto: contact/index.md

plugins:
  - mkdocs-jupyter:
      execute: False
      include_source: True
